export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SHOW_CONTACTS = 'SHOW_CONTACTS';
export const REQUEST_CONTACTS = ' REQUEST_CONTACTS ';
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
